# Generated by Django 6.0.1 on 2026-01-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mims', '0002_alter_product_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'verbose_name': 'Customer Loan', 'verbose_name_plural': 'Customer Loans'},
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='payment_method',
            field=models.CharField(default='CASH', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_unit',
            field=models.CharField(help_text='e.g., Piece', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='bulk_unit',
            field=models.CharField(help_text='e.g., Box', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='conversion_factor',
            field=models.PositiveIntegerField(help_text='Items per Box'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity_bulk',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('LOAN', 'Loan'), ('PARTIAL', 'Partial')], default='PAID', max_length=10),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity_base',
            field=models.PositiveIntegerField(),
        ),
    ]
