# Generated by Django 6.0.1 on 2026-01-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mims', '0003_alter_loan_options_alter_paymentrecord_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='buy_price_per_bulk',
            field=models.DecimalField(decimal_places=2, help_text='Buying Price per Smallest Unit', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_price_per_base',
            field=models.DecimalField(decimal_places=2, help_text='Retail Price per Smallest Unit', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_qty',
            field=models.PositiveIntegerField(default=0, help_text='Current Stock (Number of Boxes)'),
        ),
    ]
