# Generated by Django 6.0.1 on 2026-01-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mims', '0004_alter_product_buy_price_per_bulk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='quantity_base',
            field=models.PositiveIntegerField(help_text='Small units sold (e.g., Tablets)'),
        ),
    ]
