# Generated by Django 6.0.1 on 2026-01-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mims', '0005_alter_saleitem_quantity_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Date when product expires', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='buy_price_per_bulk',
            field=models.DecimalField(decimal_places=2, help_text='Buy Price per Smallest Unit', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='conversion_factor',
            field=models.PositiveIntegerField(help_text='Sellable Items per Box'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_qty',
            field=models.FloatField(default=0, help_text='Current Stock in Boxes'),
        ),
    ]
