# Generated by Django 6.0.1 on 2026-02-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mims', '0007_alter_saleitem_quantity_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
